/**
 * Keep channel names in sync with desktop/src/ipc/channels.ts
 */
export const DESKTOP_IPC = {
  WINDOW_MINIMIZE: "desktop:window:minimize",
  WINDOW_MAXIMIZE: "desktop:window:maximize",
  WINDOW_CLOSE: "desktop:window:close",
  WINDOW_IS_MAXIMIZED: "desktop:window:isMaximized",
  WINDOW_GET_STATE: "desktop:window:getState",
  DIALOG_OPEN: "desktop:dialog:open",
  DIALOG_SAVE: "desktop:dialog:save",
  DIALOG_MESSAGE: "desktop:dialog:message",
  STORE_GET: "desktop:store:get",
  STORE_SET: "desktop:store:set",
  STORE_DELETE: "desktop:store:delete",
  PRINT_SILENT: "desktop:print:silent",
  PRINT_GET_PRINTERS: "desktop:print:getPrinters",
  PRINT_TO_PDF: "desktop:print:toPdf",
  NOTIFY_SHOW: "desktop:notify:show",
  NOTIFY_SET_BADGE: "desktop:notify:setBadge",
  APP_GET_VERSION: "desktop:app:getVersion",
  APP_GET_PLATFORM: "desktop:app:getPlatform",
  APP_CHECK_API: "desktop:app:checkApi",
  SHELL_OPEN_EXTERNAL: "desktop:shell:openExternal",
  SHELL_SHOW_ITEM: "desktop:shell:showItemInFolder",
  OFFLINE_STATUS: "desktop:offline:status",
  OFFLINE_ENQUEUE: "desktop:offline:enqueue",
  OFFLINE_SYNC_NOW: "desktop:offline:syncNow",
  OFFLINE_QUEUE_STATS: "desktop:offline:queueStats",
  OFFLINE_CACHE_GET: "desktop:offline:cacheGet",
  OFFLINE_CACHE_PUT: "desktop:offline:cachePut",
  OFFLINE_CACHE_LIST: "desktop:offline:cacheList",
  OFFLINE_LOGS: "desktop:offline:logs",
  OFFLINE_SET_TOKEN: "desktop:offline:setToken",
  SEC_VAULT_GET: "desktop:sec:vaultGet",
  SEC_VAULT_SET: "desktop:sec:vaultSet",
  SEC_VAULT_DELETE: "desktop:sec:vaultDelete",
  SEC_VAULT_STATUS: "desktop:sec:vaultStatus",
  SEC_SET_CONTEXT: "desktop:sec:setContext",
  SEC_CAPABILITIES: "desktop:sec:capabilities",
  SEC_CAN: "desktop:sec:can",
  SEC_AUDIT: "desktop:sec:audit",
  SEC_AUDIT_LIST: "desktop:sec:auditList",
  SEC_DIAGNOSTICS: "desktop:sec:diagnostics",
} as const;
